---

name: Integration

env:
  redis_version: 6.0.10

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - master
      - main
      - '[0-9].[0-9]'
    schedule:
      - cron: '0 1 * * *'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: build redis
        run: |
          sudo apt-get update -q
          sudo apt-get install -y make gcc-8 g++-8 libssl-dev
      - name: build redis
        uses: actions/checkout@v3
        with:
          repository: redis/redis
          path: redis
          ref: ${{env.redis_version}}

      - name: build and install redis
        working-directory: redis
        run: |
          make
          sudo make install

      - name: run tests
        run: |
          make test
