---

name: Integration

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '**/*.rst'
    branches:
      - master
      - '[0-9].[0-9]'
  pull_request:
    branches:
      - master
      - '[0-9].[0-9]'
  schedule:
    - cron: '10 2 * * *' # nightly build

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: start redis docker
        run: docker run -p 6379:6379 -d redis:6.2
      - name: Set up java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev make gcc g++
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            /var/cache/apt
          key: spark-redis-${{hashFiles('**/pom.xml')}}
      - name: mvn offline
        run: |
          mvn -q dependency:go-offline
      - name: build and install redis
        run: |
          git clone https://github.com/redis/redis.git --branch unstable --single-branch redis-git
          make
          sudo make install
      - name: run tests
        run: |
          make test
        env:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
      - name: codecov
        run: |
          bash <(curl -s https://codecov.io/bash)
